yandex:
  geocoder:
    api_key: "52afd32b-2096-48e3-a8cf-8126cc58c620" # localhost key
#    api_key: "350d73aa-6e63-4ea4-a773-ac2baeadf011" # localhost key
#    api_key: "2b0da60a-c6f2-4567-8484-23ac0bc459f0" # ipv4 key
    requests_limit: 10000
    chunk_request_size: 10